os: linux
dist: bionic

# setup language. enables for test in Go later down the line
language: go
go:
  - "1.17"


env:
  - GO111MODULE=on

install: true

# setup services e.g. docker
services:
  - docker

jobs:
  include:
    - stage: test_PR
      name: "Run tests"
      script:
        - chmod +x -R ./scripts
        - echo "Testing go program"
        - ./scripts/run_test.sh
        - echo "Done running unittests"
        - echo "Setting up golint"
        - go get -u golang.org/x/lint/golint
        - echo "running golint"
        - ./scripts/golinter.sh
    - stage: docker-build
      name: "Build and push docker"
      script:
      - chmod +x -R ./scripts
      - echo "LOGIN"
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - echo "BUILD"
      - ./scripts/docker-build.sh
      #    - echo "PUSH"
      #    - ./scripts/docker-release.sh

stages:
  - name: test_PR
    # require the type to be a PR
    if: branch = feature/#69-travis-ci AND (type = pull_request OR type = push)


  - name: docker-build
    # require the type to be push to master
    if: type = push AND branch = master



# Inspired from https://blog.travis-ci.com/2019-05-30-setting-up-a-ci-cd-process-on-github