os: linux
dist: bionic

# setup language. enables for test in Go later down the line
language: go
go:
- 1.17

# setup services e.g. docker
services:
- docker

# custom install phase before the main install phase
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out /tmp/git_deploy_key -d
- chmod 600 /tmp/git_deploy_key
- echo 'echo ' > /tmp/askpass && chmod +x /tmp/askpass
- eval "$(ssh-agent -s)"
- DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key < /dev/null

# install phase
install:
- docker --version

stages:
  - docker-build
  - test
  - deploy

jobs:
  include:
    - stage: docker-build
      name: "Build and push docker"
      script: 
        - echo "LOGIN"
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - echo "BUILD"
        - docker build --tag $DOCKER_USERNAME/minitwit:latest . --file Dockerfile
        - echo "PUSH"
        - docker push $DOCKER_USERNAME/minitwit:latest

    - stage: test
      name: "Run tests"
      script:
        - "echo TODO"

    - stage: deploy
      name: "Deploy new version"
      script: |
        ssh -o "StrictHostKeyChecking no" ${MT_USER}/${MT_SERVER} \
        "source /root/.profile && \
        cd /vagrant && \
        docker-compose pull && \
      # start the application, but detach it, so it just runs in the back
        docker-compose up -d"

script: |
  echo "build complete"


#############
# reminders #
#############
# PHASES #########################################
# before_install - before the install phase
# before_script - before the script phase
# after_script - after the script phase.
# after_success - when the build succeeds (e.g. building documentation), the result is in TRAVIS_TEST_RESULT environment variable
# after_failure - when the build fails (e.g. uploading log files), the result is in TRAVIS_TEST_RESULT environment variable

# TEST #########################################
# https://docs.travis-ci.com/user/languages/go/
