os: linux
dist: bionic
language: go
go:
- 1.17
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_acbe53aa6784_key -iv $encrypted_acbe53aa6784_iv
  -in travis.enc -out /tmp/git_deploy_key -d
- chmod 600 /tmp/git_deploy_key
- echo 'echo ' > /tmp/askpass && chmod +x /tmp/askpass
- eval "$(ssh-agent -s)"
- DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
install:
- docker --version
script: |
  echo "build complete"
