# Server configurations
server:
  host: "localhost"
  port: 8080

# Postgresql DB
database:
  #connectionstring: "C:\\Users\\JTT\\Documents\\git\\MiniTwit\\minitwit.db"
  connectionstring: "/tmp/minitwit.db"
  #connectionstring: "C:/Users/hardk/source/repos/MiniTwit/minitwit.db"
  #connectionstring: "/home/turbo/ITU/DevOps/MiniTwit/tmp/minitwit.db"
  #connectionstring: "H:/repos/MiniTwit/minitwit.db"
