version: '3'
services:

  minitwit-main:
    container_name: minitwit-main
    image: groupddevops/minitwit-go:237df00
    environment:
      - SERVER_HOST=localhost
      - DB_TYPE=SQLite
      - DB_CONNECTION_STRING=/tmp/minitwit-main.db
    ports:
      - 8000:8080
    volumes:
      - ../data/:/tmp/

  minitwit-postgres:
    container_name: minitwit-postgres
    build: .
    environment:
      - SERVER_HOST=localhost
      - DB_TYPE=Postgres
      - DB_CONNECTION_STRING=host=database.thomsen-it.dk port=5432 user=postgres password=aVAa7BdTEMC6F9koEzPUTNAy dbname=minitwit
    ports:
      - 8080:8080
