version: '3'
services:


  minitwit-SQLite:
    container_name: minitwit-SQLite
    image: minitwit-go
    build: .
    environment:
      - SERVER_HOST=localhost
      - DB_CONNECTION_STRING=/tmp/minitwit.db
    ports:
      - 8080:8080
    volumes:
      - ../data/:/tmp/

  minitwit-Postgres:
    container_name: minitwit-Postgres
    image: minitwit-go
    build: .
    environment:
      - SERVER_HOST=localhost
      - DB_CONNECTION_STRING=host=postgres user=postgres password=password dbname=minitwit
    ports:
      - 8000:8080
    volumes:
      - ../data/:/tmp/


  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432