version: '3'
services:

  minitwit:
    build: .
    #image: groupddevops/minitwit-go:a46e0b3
    container_name: minitwit
    environment:
      - SERVER_HOST=localhost
      - DB_TYPE=Postgres
      - DB_CONNECTION_STRING=host=postgres port=5432 user=postgres password=example dbname=minitwit
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:13.5
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./docker-data/postgres/:/var/lib/postgresql/data
    #user: '1000'

  prometheus:
    image: prom/prometheus:v2.33.5
    container_name: prometheus
    volumes:
      - ./docker-data/prometheus/config/:/etc/prometheus/
      - ./docker-data/prometheus/internal/:/prometheus/
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.4.3
    container_name: grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - DATABASE_HOSTNAME=$DATABASE_HOSTNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - GF_INSTALL_PLUGINS=marcusolsson-hourly-heatmap-panel,grafana-image-renderer
    ports:
      - "3000:3000"
    volumes:
      - ./docker-data/grafana/internal/:/var/lib/grafana/
      - ./docker-data/grafana/provisioning/:/etc/grafana/provisioning/
      - ./docker-data/grafana/dashboards/:/etc/grafana/dashboards/
    user: '0'

  data-scraper:
    image: groupddevops/data-scraper:f16c0db
    container_name: data-scraper
    environment:
      - INTERVAL=5
    ports:
      - "8000:8080"

