version: '3'
services:

  minitwit:
    build: .
    #image: groupddevops/minitwit-go:a46e0b3
    container_name: minitwit
    environment:
      - SERVER_HOST=localhost
      - DB_TYPE=Postgres
      - DB_CONNECTION_STRING=host=postgres port=5432 user=postgres password=example dbname=minitwit
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: docker.{{.Name}}

  postgres:
    image: postgres:13.5
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=minitwit
    volumes:
      - ./docker-data/postgres/:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.33.5
    container_name: prometheus
    volumes:
      - ./docker-data/prometheus/config/:/etc/prometheus/
      - ./docker-data/prometheus/internal/:/prometheus/
    ports:
      - "9090:9090"
    user: "0"

  grafana:
    image: grafana/grafana:8.4.3
    container_name: grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - DATABASE_HOSTNAME=$DATABASE_HOSTNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL
      - GF_INSTALL_PLUGINS=marcusolsson-hourly-heatmap-panel
    ports:
      - "3000:3000"
    volumes:
      - ./docker-data/grafana/internal/:/var/lib/grafana/
      - ./docker-data/grafana/provisioning/:/etc/grafana/provisioning/
      - ./docker-data/grafana/dashboards/:/etc/grafana/dashboards/
    depends_on:
      - loki
    user: "0"

  data-scraper:
    image: groupddevops/data-scraper:f16c0db
    container_name: data-scraper
    environment:
      - INTERVAL=5

  fluentd:
    image: grafana/fluent-plugin-loki:master
    container_name: fluentd
    command:
      - "fluentd"
      - "-v"
      - "-p"
      - "/fluentd/plugins"
    environment:
      LOKI_URL: http://host.docker.internal:3100
      LOKI_USERNAME:
      LOKI_PASSWORD:
    ports:
      - "24224:24224"
    volumes:
      - ./docker-data/fluentd/config/fluentd.conf:/fluentd/etc/fluent.conf

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker-data/nginx/:/etc/nginx/
    logging:
      driver: fluentd
      options:
        tag: docker.{{.Name}}
    depends_on:
      - minitwit
      - fluentd

  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./docker-data/loki/config/:/etc/loki/
      - ./docker-data/loki/internal/:/tmp/loki/

    command: -config.file=/etc/loki/loki.yaml
    user: "0"
