version: '3'
services:

  minitwit:
    container_name: minitwit
    build: .
    environment:
      - SERVER_HOST=localhost
      - DB_TYPE=Postgres
      - DB_CONNECTION_STRING=host=localhost port=5432 user=postgres password=example dbname=minitwit
    ports:
      - 8080:8080
