version: '3'
services:

  minitwit-main:
    container_name: minitwit-main
    image: groupddevops/minitwit-go:237df00
    environment:
      - SERVER_HOST=localhost
      - DB_TYPE=SQLite
      - DB_CONNECTION_STRING=/tmp/minitwit-main.db
    ports:
      - 8000:8080
    volumes:
      - ../data/:/tmp/
    depends_on:
      - grafana
      - prometheus

  minitwit-postgres:
    container_name: minitwit-postgres
    build: .
    environment:
      - SERVER_HOST=localhost
      - DB_TYPE=Postgres
      - DB_CONNECTION_STRING=host=database.thomsen-it.dk port=5432 user=postgres password=example dbname=minitwit
    ports:
      - 8080:8080
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"


  grafana:
    build:
      context: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

# Explicitly define the persistent volume for your data storage
volumes:
  grafana-data:
