# from https://grafana.com/docs/grafana/latest/administration/provisioning/
notifiers:
  - name: discord-channel
    type: discord
    uid: discordGrafana
    org_id: 1
    is_default: true
    frequency: 1h
    settings:
      use_discord_username: true
      url: https://discord.com/api/webhooks/957216287422050354/kQ2zNumEEkI7nH7wd4xKbu_mmydmifo8p4dtzccDqedEA_QjMaJvijO4IMFW9BySadrV
    secure_settings:
      url: https://discord.com/api/webhooks/957216287422050354/kQ2zNumEEkI7nH7wd4xKbu_mmydmifo8p4dtzccDqedEA_QjMaJvijO4IMFW9BySadrV

delete_notifiers:
  - name: discord-channel
    uid: discordGrafana
    org_id: 1