version: '3'
services:
  sqlite:
    container_name: sqlite
    image: nouchka/sqlite3:latest

    volumes:
      - ./data/minitwit/:/tmp/
    command: /tmp/minitwit-bak.db "UPDATE user SET pw_hash='pbkdf2:sha256:50000' || '$$' || 'CCWW6o8F' || '$$' || 'c3f9294679a99b7da156d4f267be5dcee37afebba25e3c893c8dd67e78513cb9'"

# https://stackoverflow.com/questions/6776657/how-to-change-a-value-in-a-column-on-a-sqlite-database

# This did not work.
# https://database.guide/2-ways-to-insert-a-new-line-into-a-string-in-sqlite/
# x'70626B646...' = pbkdf2:sha256:50000$CCWW6o8F$c3f9294679a99b7da156d4f267be5dcee37afebba25e3c893c8dd67e78513cb9

# https://www.sqlitetutorial.net/sqlite-update/

  # 'pbkdf2:sha256:50000' || '$' || 'CCWW6o8F' || '$' || 'c3f9294679a99b7da156d4f267be5dcee37afebba25e3c893c8dd67e78513cb9'"

  # invalid interpolation format for services.sqlite.command: "/tmp/minitwit-bak.db \"UPDATE user SET pw_hash='pbkdf2:sha256:50000' || '$' || 'CCWW6o8F' || '$' || 'c3f9294679a99b7da156d4f267be5dcee37afebba25e3c893c8dd67e78513cb9'\"". Yo
  # u may need to escape any $ with another $.
  # Error: No such container: sqlite.. Thanks..

  # 'pbkdf2:sha256:50000' || '$$' || 'CCWW6o8F' || '$$' || 'c3f9294679a99b7da156d4f267be5dcee37afebba25e3c893c8dd67e78513cb9'