{
 "title": "Alerts",
 "time": { "from": "2022-03-19T03:09:08.212Z", "to": "2022-04-02T01:09:08.212Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ram usage",
   "type": "timeseries",
   "description": "Alerts if ram usage is above 75% for 15 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node-exporter\"} * 100) / node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "Alerts when disk usage is above 50% for 15 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{job=\"node-exporter\",device!~'rootfs'})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Avg. Response time",
   "type": "timeseries",
   "description": "Alerts if avg response time is above 10 ms for 5 min or that it increases by 8 ms",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(minitwit_latest_time) / 10^9"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Alerts if number of errors increases by 10 for 1 minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(minitwit_total_http{code!~\"2.*|3.*\"})",
     "legendFormat": "Error Summation"
    }
   ]
  }
 ]
}