{
 "title": "Endpoint",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Endpoint response times (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "minitwit_endpoint_responsetime/10^9",
     "legendFormat": "{{url}} {{method}}"
    }
   ]
  },
  {
   "title": "Errorcodes + url",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (url, code) (minitwit_total_http)",
     "legendFormat": "{{url}} {{code}}"
    }
   ]
  },
  {
   "title": "Average respond times per endpoint (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(minitwit_endpoint_avg_responsetime_sum/minitwit_endpoint_avg_responsetime_count)/10^9",
     "legendFormat": "{{url}} {{method}} ({{code}})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "description": "Distribution of response times",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(minitwit_endpoint_responsetime_histogram_bucket[5m])) by(le))",
     "legendFormat": "95 Quantile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(minitwit_endpoint_responsetime_histogram_bucket[5m])) by(le))",
     "legendFormat": "90 Quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(minitwit_endpoint_responsetime_histogram_bucket[5m])) by(le))",
     "legendFormat": "50 Quantile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(minitwit_endpoint_responsetime_histogram_bucket[5m])) by(le))",
     "legendFormat": "10 Quantile"
    },
    {
     "expr": "histogram_quantile(0.05, sum(rate(minitwit_endpoint_responsetime_histogram_bucket[5m])) by(le))",
     "legendFormat": "5 Quantile"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "description": "Amount of status codes returned that is not 2xx or 3xx",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (minitwit_total_http{code!~\"2.*|3.*\"})"
    }
   ]
  },
  {
   "title": "HTTP Requests (Per code)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (minitwit_total_http)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (minitwit_total_http)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Error Procentage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(minitwit_total_http{code!~\"2.*|3.*\"}) / 2)\n/\n(sum(minitwit_total_http / 2))"
    }
   ]
  },
  {
   "title": "Endpoints with errors",
   "type": "bargauge",
   "description": "Entries in this panel have a status code that is not 2xx or 3xx.",
   "gridPos": { "h": 14, "w": 7, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (url, code) (minitwit_total_http{code!~\"2.*|3.*\"})",
     "legendFormat": "{{url}} {{code}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 22 },
   "targets": [
    {
     "expr": "(sum(increase(minitwit_total_http{code!~\"2.*|3.*\"}[$__interval])))\n/\n(sum(increase(minitwit_total_http[$__interval])))",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Average Response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(minitwit_latest_time)/10^6" }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 29 },
   "targets": [
    { "expr": "avg(minitwit_latest_time)/10^6" }
   ]
  }
 ]
}