{
 "title": "Heatmaps",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(minitwit_total_http[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Successful HTTP Requests",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(minitwit_total_http{code=~\"2.*|3.*\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Failed HTTP Requests",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(minitwit_total_http{code=~\"4.*|5.*\"}[$__interval]))"
    }
   ]
  }
 ]
}