{
 "title": "Minitwit - Business Intelligence",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Registered Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM \"user\""
    }
   ]
  },
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM \"message\"\n"
    }
   ]
  },
  {
   "title": "Follow",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM \"follower\"\n"
    }
   ]
  },
  {
   "title": "Latest",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minitwit_latest{instance=\"minitwit:8080\"}"
    }
   ]
  },
  {
   "title": "Top 10 Following users",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select count(*), u.username\nfrom follower f\n    join \"user\" u on u.user_id = f.who_id\ngroup by who_id, u.username\norder by count(*) desc\nlimit 10"
    }
   ]
  },
  {
   "title": "Top 10 Followed users",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select count(*), u.username\nfrom follower f\n    join \"user\" u on u.user_id = f.who_id\ngroup by whom_id, u.username\norder by count(*) desc\nlimit 10"
    }
   ]
  },
  {
   "title": "Top 10 Twitters",
   "type": "barchart",
   "description": "Users who twits the most",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select count(*), u.username\nfrom message m\n         join \"user\" u on u.user_id = m.author_id\ngroup by m.author_id, u.username\norder by count(*) desc\nlimit 10\n"
    }
   ]
  }
 ]
}