{
 "title": "Endpoint",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Endpoint response times (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "minitwit_endpoint_responsetime/10^9",
     "legendFormat": "{{url}} {{method}}"
    }
   ]
  },
  {
   "title": "Errorcodes + url",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (url, code) (minitwit_total_http)",
     "legendFormat": "{{url}} {{code}}"
    }
   ]
  },
  {
   "title": "Average respond times per endpoint (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(minitwit_endpoint_avg_responsetime_sum/minitwit_endpoint_avg_responsetime_count)/10^9",
     "legendFormat": "{{url}} {{method}} ({{code}})"
    }
   ]
  },
  {
   "title": "Total errors (not 2.. or 3..)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (minitwit_total_http{code!~\"2.*|3.*\"})"
    }
   ]
  },
  {
   "title": "Errorcodes + url",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (url, code) (minitwit_total_http{code!~\"2.*|3.*\"})",
     "legendFormat": "{{url}} {{code}}"
    }
   ]
  },
  {
   "title": "HTTP Requests (Per code)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (minitwit_total_http)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (minitwit_total_http)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Average Handling Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(minitwit_latest_time)/10^9" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } }
 ]
}