name: Lint, Build, Test go app CI

on:
 push:
    branches: [ feature/#117_Setup_Github_action_as_CI ]

jobs:

#  LintAndTest:

#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - uses: actions/cache@v2
#      with:
#        path: ~/go/pkg/mod
#        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#        restore-keys: |
#          ${{ runner.os }}-go-
#
#    - name: Shellcheck the script folder
#      run: make shellcheck
#
#    - name: Set up Go
#      uses: actions/setup-go@v2
#      with:
#        go-version: 1.17
#
#
#    - name: Get dependencies
#      run: make deps
#
#    - name: Run linter
#      run: make go_lint
#
#    - name: Run tests
#      run: make test
#
#  scancode:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run Scancode on the project
#        run: make scancode

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # From https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
      # This is the a separate action that sets up buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # So now you can use Actions' own caching!
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: docker linting
        run: make docker_lint

      - name: Build docker image
        run: make docker-build

      - name: Release docker image
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./scripts/docker-release.sh groupddevops $DOCKER_PASSWORD test

      # DOES NOT WORK YET
      #- name: Scan docker image
      #  run: make docker-scan
      
      # DOES WORK 
      #- uses: azure/container-scan@v0
      #  with:
      #    image-name: gominitwit:latest

