on:
  push:
    branches:
      - dev
      - main
      - feature/#114-TD-tools
  pull_request:
      types: [opened, synchronize, reopened]
name: Technical Debt Estimation Tools

jobs:
# Code Climate
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm init
        run: npm init -y
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.3
      env:
        CC_TEST_REPORTER_ID: <code_climate_reporter_id>
      with:
        coverageCommand: npm run coverage
        debug: true
# Sonar Cloud
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}