name: Makefile CI

on:
  push:
    branches: [ feature/#117_Setup_Github_action_as_CI ]
  pull_request:
    branches: [ feature/#117_Setup_Github_action_as_CI ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

          
    - name: Get dependencies
      run: make deps
      
    - name: Run linter
      run: make go_lint

    - name: Run tests
      run: make test