name: Makefile CI

on:
  push:
    branches: [ feature/#117_Setup_Github_action_as_CI ]
  pull_request:
    branches: [ feature/#117_Setup_Github_action_as_CI ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Get dependencies
      run: make deps
      
    - name: Run linter
      run: make go_lint

    - name: Run tests
      run: make test